---
- name: Refresh package lists
  apt:
    update_cache: yes
  tags: essential-packages

- name: Install some essential packages
  apt:
    name:
      - apt-transport-https
      - build-essential
      - ca-certificates
      - curl
      - git-core
      - graphviz
      - lsb-release
      - python-mysqldb
      - python-passlib
      - python-psycopg2
      - python-pycurl
      - python3-software-properties
      - sudo
      - vim
      - nodejs
    state: present
  tags: essential-packages
