---
- import_tasks: start.yml
- import_tasks: clone.yml
- import_tasks: files.yml
- import_tasks: env.yml
  when: current_app.env is defined
- import_tasks: composer.yml
- import_tasks: passport.yml
  when: current_app.passport is defined and current_app.passport == True
- import_tasks: migrate.yml
- import_tasks: npm.yml
- import_tasks: optimize.yml
- import_tasks: post-deploy.yml
- import_tasks: finish.yml
- import_tasks: restart-workers.yml
