---
- name: Provision servers in {{ env }}
  hosts: "{{ env }}"
  become: yes
  remote_user: root
  roles:
    - role: basics
      tags: basics
    - role: geerlingguy.nodejs
    - role: users
      tags: users
    - role: geerlingguy.ntp
      tags: [basics, ntp]
    - role: kamaln7.swapfile
      tags: [basics, swapfile]
    - role: network-basics
      tags: network-basics
    - role: postgres
      tags: [database, postgres]
      when: postgres_required
    - role: mariadb
      tags: [database, mariadb]
      when: mariadb_required
    - role: php
      tags: php
    - role: nginx
      tags: nginx
    - role: geerlingguy.composer
      tags: composer
    - role: docker
      tags: docker
    - role: letsencrypt
      tags: [letsencrypt, certs]
    - role: databases
      tags: databases
    - role: per-app
      tags: per-app
    - role: logrotate
      tags: [logrotate, per-app]
    - role: queue
      tags: queue
    - role: backup
      tags: backup
